// Code generated by "stringer -type=SslType"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[disable-0]
	_ = x[enable-1]
}

const _SslType_name = "disableenable"

var _SslType_index = [...]uint8{0, 7, 13}

func (i SslType) String() string {
	if i < 0 || i >= SslType(len(_SslType_index)-1) {
		return "SslType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SslType_name[_SslType_index[i]:_SslType_index[i+1]]
}
