// Code generated by "stringer -type=Commands"; DO NOT EDIT.

package pool

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[nothing-0]
	_ = x[get-1]
	_ = x[set-2]
	_ = x[getIfNotAnyFree-3]
}

const _Commands_name = "nothinggetsetgetIfNotAnyFree"

var _Commands_index = [...]uint8{0, 7, 10, 13, 28}

func (i Commands) String() string {
	if i < 0 || i >= Commands(len(_Commands_index)-1) {
		return "Commands(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Commands_name[_Commands_index[i]:_Commands_index[i+1]]
}
