// Code generated by "stringer -type=Types"; DO NOT EDIT.

package pool

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[none-0]
	_ = x[postgres-1]
	_ = x[oracle-2]
	_ = x[msSql-3]
	_ = x[redis-4]
	_ = x[mySql-5]
	_ = x[kafka-6]
	_ = x[ibmMq-7]
	_ = x[rabbit-8]
}

const _Types_name = "nonepostgresoraclemsSqlredismySqlkafkaibmMqrabbit"

var _Types_index = [...]uint8{0, 4, 12, 18, 23, 28, 33, 38, 43, 49}

func (i Types) String() string {
	if i < 0 || i >= Types(len(_Types_index)-1) {
		return "Types(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Types_name[_Types_index[i]:_Types_index[i+1]]
}
