// Code generated by "stringer -type=IdTypes"; DO NOT EDIT.

package customer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[none-0]
	_ = x[Card-1]
	_ = x[Passport-2]
	_ = x[GovernmentPaper-3]
}

const _IdTypes_name = "noneCardPassportGovernmentPaper"

var _IdTypes_index = [...]uint8{0, 4, 8, 16, 31}

func (i IdTypes) String() string {
	if i < 0 || i >= IdTypes(len(_IdTypes_index)-1) {
		return "IdTypes(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IdTypes_name[_IdTypes_index[i]:_IdTypes_index[i+1]]
}
