// Code generated by "stringer -type=Status"; DO NOT EDIT.

package customer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Active-1]
	_ = x[Inactive-2]
	_ = x[Banned-3]
	_ = x[Expired-4]
	_ = x[Deceased-5]
}

const _Status_name = "UnknownActiveInactiveBannedExpiredDeceased"

var _Status_index = [...]uint8{0, 7, 13, 21, 27, 34, 42}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
