// Code generated by "stringer -type=Types"; DO NOT EDIT.

package customer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[none-0]
	_ = x[Card-1]
	_ = x[Passport-2]
	_ = x[GovernmentPaper-3]
}

const _Types_name = "noneCardPassportGovernmentPaper"

var _Types_index = [...]uint8{0, 4, 8, 16, 31}

func (i Types) String() string {
	if i < 0 || i >= Types(len(_Types_index)-1) {
		return "Types(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Types_name[_Types_index[i]:_Types_index[i+1]]
}
