// Code generated by "stringer -type=Types"; DO NOT EDIT.

package error

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[runTime-0]
	_ = x[System-1]
	_ = x[general-2]
	_ = x[notImplemented-3]
	_ = x[notSupported-4]
	_ = x[reserved1-5]
	_ = x[reserved2-6]
	_ = x[reserved3-7]
	_ = x[reserved4-8]
	_ = x[database-9]
	_ = x[customer-10]
	_ = x[city-11]
	_ = x[country-12]
	_ = x[pool-13]
	_ = x[loader-14]
	_ = x[address-15]
	_ = x[config-16]
}

const _Types_name = "runTimeSystemgeneralnotImplementednotSupportedreserved1reserved2reserved3reserved4databasecustomercitycountrypoolloaderaddressconfig"

var _Types_index = [...]uint8{0, 7, 13, 20, 34, 46, 55, 64, 73, 82, 90, 98, 102, 109, 113, 119, 126, 132}

func (i Types) String() string {
	if i < 0 || i >= Types(len(_Types_index)-1) {
		return "Types(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Types_name[_Types_index[i]:_Types_index[i+1]]
}
