// Code generated by "stringer -type=CCommands"; DO NOT EDIT.

package pool

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[nothing-0]
	_ = x[get-1]
	_ = x[set-2]
	_ = x[getIfNotAnyFree-3]
}

const _CCommands_name = "nothinggetsetgetIfNotAnyFree"

var _CCommands_index = [...]uint8{0, 7, 10, 13, 28}

func (i CCommands) String() string {
	if i < 0 || i >= CCommands(len(_CCommands_index)-1) {
		return "CCommands(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CCommands_name[_CCommands_index[i]:_CCommands_index[i+1]]
}
