// Code generated by "stringer -type=CTypes"; DO NOT EDIT.

package pool

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[none-0]
	_ = x[postgres-1]
	_ = x[oracle-2]
	_ = x[msSql-3]
	_ = x[redis-4]
	_ = x[mySql-5]
	_ = x[kafka-6]
	_ = x[ibmMq-7]
	_ = x[rabbit-8]
}

const _CTypes_name = "nonepostgresoraclemsSqlredismySqlkafkaibmMqrabbit"

var _CTypes_index = [...]uint8{0, 4, 12, 18, 23, 28, 33, 38, 43, 49}

func (i CTypes) String() string {
	if i < 0 || i >= CTypes(len(_CTypes_index)-1) {
		return "CTypes(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CTypes_name[_CTypes_index[i]:_CTypes_index[i+1]]
}
